source "https://rubygems.org"

gem "rails"
gem "httparty"
gem "rake"
gem "google-protobuf"
gem "yard", "~> 0.8.7.6"
gem "protobuf"
gem "markdown"
gem "barkdown"
gem "larkdown"
gem "sharkdown"
gem "sharktown"
gem "sharklounge"
