source "https://rubygems.org"

gem "butterfly"
gem "in"
gem "the"
gem "sky"

gem "I"
gem "can"
gem "fly"
gem "twice"
gem "as"
gem "high"

gem "take"
gem "a"
gem "look"

gem "its"
gem "in"
gem "a"
gem "book"

gem "a"
gem "reading"
gem "rainbow"
